export const images = {
    AbstractReflections: require('../../assets/images/AbstractReflections.jpg'),
    AbstractSymphonyMusicInspiredModernArtCanvas: require('../../assets/images/AbstractSymphonyMusicInspiredModernArtCanvas.jpg'),
    TheLastLightEchoesofMyYouth: require('../../assets/images/TheLastLightEchoesofMyYouth.jpg'),
    CityLights: require('../../assets/images/CityLights.jpg'),
    FridaKahloJungleCatLovesEver: require('../../assets/images/FridaKahloJungleCatLovesEver.jpg'),
    FusionElements: require('../../assets/images/FusionElements.jpg'),
    GirlWithAPearlEarring: require('../../assets/images/GirlWithAPearlEarring.jpg'),
    MoreThanJustArtItsAFeeling: require('../../assets/images/MoreThanJustArtItsAFeeling.jpg'),
    PinkLotuses: require('../../assets/images/PinkLotuses.jpg'),
    RedPoppy: require('../../assets/images/RedPoppy.jpg'),
    SelfPortraitWithThornNecklace: require('../../assets/images/SelfPortraitWithThornNecklace.jpg'),
    StarryNightOverTheRhone: require('../../assets/images/StarryNightOverTheRhone.jpg'),
    Sunflowers: require('../../assets/images/Sunflowers.jpg'),
    // TheLastLightEchoesOfMyYouth: require('../../assets/images/TheLastLightEchoesOfMyYouth.jpg'),
    TimelessBeautyBlackAndWhitePhotography: require('../../assets/images/TimelessBeautyBlackAndWhitePhotography.jpg'),
    UrbanEscapeVibrantCityscapeFramedPainting: require('../../assets/images/UrbanEscapeVibrantCityscapeFramedPainting.jpg'),
    WaterLiliesSeries12: require('../../assets/images/WaterLiliesSeries12.jpg'),
    WhereImaginationMeetsTheCanvas: require('../../assets/images/WhereImaginationMeetsTheCanvas.jpg'),
    WhispersOfColorsInSilentShadows: require('../../assets/images/WhispersOfColorsInSilentShadows.jpg'),
    ABrushstrokeOfSerenityInAChaoticWorld: require('../../assets/images/ABrushstrokeOfSerenityInAChaoticWorld.jpg'),
    WhereStillnessSpeaksColorsConverse: require('../../assets/images/WhereStillnessSpeaksColorsConverse.jpg'),
};